branches:
  only:
    - master

before_install:
  - gem uninstall -v '>= 2' -i $(rvm gemdir)@global -ax bundler || true
  - gem install bundler:1.17.3

language: ruby
cache: bundler
rvm:
  - 2.1
  - 2.6.1
  - 3.0.0
